from abc import ABC, abstractmethod


class Client(ABC):
    @abstractmethod
    async def pre_hell_started(self): ...
    @abstractmethod
    async def hell_started(self): ...
    @abstractmethod
    async def pre_hell_finished(self): ...
    @abstractmethod
    async def hell_finished(self): ...
